[profile.default]
optimizer_runs = 1000000
verbosity = 1

# Extreme Fuzzing CI Profile :P
[profile.ci]
fuzz_runs = 100_000
verbosity = 4

[rpc_endpoints]
goerli = "${RPC_URL_GOERLI}"
sepolia = "${RPC_URL_SEPOLIA}"
mainnet = "${RPC_URL_MAINNET}"

[etherscan]
goerli = { key = "${ETHERSCAN_KEY}", url = "https://api-goerli.etherscan.io/api" }
sepolia = { key = "${ETHERSCAN_KEY}", url = "https://api-sepolia.etherscan.io/api" }
mainnet = { key = "${ETHERSCAN_KEY}" }
